### ISSUE TITLE
Affiliations not quite right

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#75]
As shown below: 

![image](https://github.com/nptscot/networkmerge/assets/1825120/351f8612-c91f-4428-aecd-1782489661d9)

Source: https://nptscot.github.io/networkmerge/paper.html

Any ideas how to fix this anyone?

Offending lines of code:

https://github.com/nptscot/networkmerge/blob/f3a4663b593dcc2a6ef0290500528530849c9e84/paper.qmd#L8-L27

**Comment by JosiahParry** [comment]
Here's a working approach: 

```yaml
title: "Route network simplification for transport planning"
authors: 
  - name: Robin Lovelace
    affiliation: 
      - ref: 1
    orcid: 0000-0001-5679-6536
  - name: Zhao Wang
    affiliation:
      - ref: 1
    orcid: 0000-0002-4054-0533
  - name: Will Deakin
    affiliation: 
      - ref: 2
    # orcid: 0009-0008-5656-4469
  - name: Josiah Parry
    affiliations: 
      - ref: 3
    orcid: 0000-0001-9910-865X
affiliations: 
  - name: Leeds Institute for Transport Studies, University of Leeds, UK
    id: 1
  - name: Network Rail, UK
    id: 2
  - name: ESRI, USA
    id: 3
format:
  html: default
```
